/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BSelect: typeof import('bootstrap-vue-next')['BSelect']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    Button: typeof import('./src/components/Button.vue')['default']
    ExpItem: typeof import('./src/components/ExpItem.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
